"""Render the archive table in README.md from each repo's results/headline.json.

Each research repo exports ``results/headline.json`` (schema ``headline/v1``).
``scripts/headline_sources.json`` pins the commit read from each repo and the
row order. This script fetches those files at the pinned commits, renders the
table and the "Other work" line, and rewrites the block between the GENERATED
markers in README.md. Every key stat links to the artifact that holds it, at
the commit named in that repo's headline.json.

Usage:
    python scripts/render_readme.py            # rewrite README.md
    python scripts/render_readme.py --check    # exit 1 if README.md is stale
    python scripts/render_readme.py --local-root /path/to/clones
        # read <root>/<repo> via `git show <commit>:results/headline.json`
        # instead of fetching from GitHub
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
SOURCES = ROOT / "scripts" / "headline_sources.json"
BEGIN = "<!-- BEGIN GENERATED: scripts/render_readme.py -->"
END = "<!-- END GENERATED -->"

MARKS = {
    "reproduced": "",
    "repo-reported, not reproduced": "†",
    "predates fix; pending re-run": "‡",
}
LEGEND = (
    "Generated by `scripts/render_readme.py` from each repo's `results/headline.json`; "
    "every key stat links to the file that holds it, at the commit that headline "
    "file names. Unmarked stats were recomputed from that file. † repo-reported, not reproduced (the inputs are licensed or no longer "
    "retrievable). ‡ produced before a code fix; a re-run is pending (see the "
    "repo's `RERUN_RUNBOOK.md`)."
)
REQUIRED_ROW_KEYS = {
    "id", "section", "hypothesis", "verdict", "verdict_detail",
    "mechanism", "stats", "caveats",
}
REQUIRED_STAT_KEYS = {"label", "display", "value", "artifact", "locator", "provenance"}


def load_headline(owner: str, repo: str, commit: str, local_root: Path | None) -> dict:
    if local_root is not None:
        out = subprocess.run(
            ["git", "-C", str(local_root / repo), "show", f"{commit}:results/headline.json"],
            check=True, capture_output=True, text=True,
        ).stdout
        return json.loads(out)
    url = f"https://raw.githubusercontent.com/{owner}/{repo}/{commit}/results/headline.json"
    with urllib.request.urlopen(url, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def validate(doc: dict, repo: str) -> None:
    if doc.get("schema") != "headline/v1":
        raise ValueError(f"{repo}: unexpected schema {doc.get('schema')!r}")
    sha = doc.get("source_commit", "")
    if len(sha) != 40 or any(c not in "0123456789abcdef" for c in sha):
        raise ValueError(f"{repo}: source_commit must be a full sha, got {sha!r}")
    for row in doc["rows"]:
        missing = REQUIRED_ROW_KEYS - row.keys()
        if missing:
            raise ValueError(f"{repo}/{row.get('id')}: missing {sorted(missing)}")
        for stat in row["stats"]:
            missing = REQUIRED_STAT_KEYS - stat.keys()
            if missing:
                raise ValueError(f"{repo}/{row['id']}: stat missing {sorted(missing)}")
            if stat["provenance"] not in MARKS:
                raise ValueError(f"{repo}/{row['id']}: unknown provenance {stat['provenance']!r}")


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def sentence(text: str) -> str:
    text = cell(text)
    return text[:1].upper() + text[1:]


def render_stat(owner: str, repo: str, sha: str, stat: dict) -> str:
    url = f"https://github.com/{owner}/{repo}/blob/{sha}/{stat['artifact']}"
    return f"{cell(stat['label'])}: [{cell(stat['display'])}]({url}){MARKS[stat['provenance']]}"


def render_verdict(row: dict) -> str:
    verdict = f"**{cell(row['verdict'])}**"
    if row["verdict_detail"]:
        verdict += f": {cell(row['verdict_detail'])}"
    return verdict


def render(sources: dict, local_root: Path | None) -> str:
    owner = sources["owner"]
    docs: dict[str, dict] = {}
    for repo, commit in sources["commits"].items():
        doc = load_headline(owner, repo, commit, local_root)
        validate(doc, repo)
        docs[repo] = doc

    rows_by_key = {
        (repo, row["id"]): row for repo, doc in docs.items() for row in doc["rows"]
    }
    listed = {tuple(k) for k in sources["archive"]} | {tuple(k) for k in sources["other"]}
    unlisted = sorted(set(rows_by_key) - listed)
    if unlisted:
        raise ValueError(f"rows exported but not placed in headline_sources.json: {unlisted}")

    lines = [
        "| Hypothesis | Repo | Verdict | Mechanism | Key stat |",
        "|---|---|---|---|---|",
    ]
    for repo, row_id in sources["archive"]:
        row = rows_by_key[(repo, row_id)]
        if row["section"] != "archive":
            raise ValueError(f"{repo}/{row_id} is not an archive row")
        sha = docs[repo]["source_commit"]
        stats = "<br>".join(render_stat(owner, repo, sha, s) for s in row["stats"])
        lines.append(
            f"| {cell(row['hypothesis'])} "
            f"| [{repo}](https://github.com/{owner}/{repo}) "
            f"| {render_verdict(row)} "
            f"| {cell(row['mechanism'])} "
            f"| {stats} |"
        )
    lines += ["", LEGEND]

    for repo, row_id in sources["other"]:
        row = rows_by_key[(repo, row_id)]
        sha = docs[repo]["source_commit"]
        stats = "; ".join(render_stat(owner, repo, sha, s) for s in row["stats"])
        lines += [
            "",
            f"**Other work:** [{repo}](https://github.com/{owner}/{repo}): "
            f"{cell(row['hypothesis'])}. {render_verdict(row)}. "
            f"{sentence(row['mechanism'])} ({stats}).",
        ]
    return "\n".join(lines)


def splice(readme: str, block: str) -> str:
    head, sep, rest = readme.partition(BEGIN)
    if not sep or END not in rest:
        raise ValueError("README.md is missing the GENERATED markers")
    _, _, tail = rest.partition(END)
    return f"{head}{BEGIN}\n{block}\n{END}{tail}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if README.md is stale")
    parser.add_argument("--local-root", type=Path, help="read headline.json from local clones")
    args = parser.parse_args()

    sources = json.loads(SOURCES.read_text(encoding="utf-8"))
    current = README.read_text(encoding="utf-8")
    updated = splice(current, render(sources, args.local_root))
    if args.check:
        if updated != current:
            print("README.md is stale; run scripts/render_readme.py", file=sys.stderr)
            return 1
        print("README.md is up to date")
        return 0
    README.write_text(updated, encoding="utf-8")
    print("README.md rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
